baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Xps's Blog"

theme = 'FixIt'
defaultContentLanguage = 'zh-cn'

[[menu.main]]
  name = "关于我们"
  url = "/about/"
  weight = 2


ignoreLogs = ['warning-dev-version']

